"""empty message

Revision ID: 3772173ea094
Revises: 
Create Date: 2016-12-27 15:41:30.262177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3772173ea094'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_names',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('character_owner_hash', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character_names.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('linked_characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character_names.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('character_authorizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('linked_character_id', sa.Integer(), nullable=True),
    sa.Column('authorization', sa.String(), nullable=True),
    sa.Column('refresh', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['linked_character_id'], ['linked_characters.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_authorizations')
    op.drop_table('linked_characters')
    op.drop_table('users')
    op.drop_table('character_names')
    # ### end Alembic commands ###
