"""empty message

Revision ID: a92b1fd335f8
Revises: 4b6fa1e7d7c0
Create Date: 2016-12-27 19:33:49.501310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92b1fd335f8'
down_revision = '4b6fa1e7d7c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character_authorizations', 'authorization',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('character_authorizations', 'refresh',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('character_names', sa.Column('last_updated', sa.DateTime(), nullable=False))
    op.alter_column('character_names', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('linked_characters', 'character_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('linked_characters', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'character_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'character_owner_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'character_owner_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'character_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('linked_characters', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('linked_characters', 'character_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('character_names', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('character_names', 'last_updated')
    op.alter_column('character_authorizations', 'refresh',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('character_authorizations', 'authorization',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
